### ISSUE TITLE
Not working on Windows due to termion dep. failing to build.

### ISSUE THREAD

**Issue by federico-r-figueredo** [fadeevab/design-patterns-rust#12]
Greetings, it seems it's not working on Windows due to **termion** not building.

I get this after `git clone & run --bin command`

![image](https://user-images.githubusercontent.com/49570839/236706183-3d5f019d-e47f-42e0-b6d0-d16238eba7e6.png)

**Comment by fadeevab** [comment]
@federico-r-figueredo It should be fixed now, verify, please!
