### ISSUE TITLE
cargo check failed in "command "

### ISSUE THREAD

**Issue by huangyt** [fadeevab/design-patterns-rust#9]
PS F:\learn\design-patterns-rust\behavioral\command> cargo check
    Checking num-iter v0.1.43
    Checking num-rational v0.4.1
    Checking termion v1.5.6
error[E0433]: failed to resolve: maybe a missing crate `sys`?
  --> D:\rust\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.5.6\src\lib.rs:24:9
   |
24 | pub use sys::size::terminal_size;
   |         ^^^ maybe a missing crate `sys`?
   |
   = help: consider adding `extern crate sys` to use the `sys` crate

error[E0433]: failed to resolve: maybe a missing crate `sys`?
  --> D:\rust\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.5.6\src\lib.rs:27:9
   |
27 | pub use sys::tty::{is_tty, get_tty};
   |         ^^^ maybe a missing crate `sys`?
   |
   = help: consider adding `extern crate sys` to use the `sys` crate

error[E0433]: failed to resolve: maybe a missing crate `sys`?
 --> D:\rust\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.5.6\src\async.rs:5:5
  |
5 | use sys::tty::get_tty;
  |     ^^^ maybe a missing crate `sys`?
  |
  = help: consider adding `extern crate sys` to use the `sys` crate

error[E0433]: failed to resolve: maybe a missing crate `sys`?
  --> D:\rust\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.5.6\src\raw.rs:28:5
   |
28 | use sys::attr::{get_terminal_attr, raw_terminal_attr, set_terminal_attr};
   |     ^^^ maybe a missing crate `sys`?
   |
   = help: consider adding `extern crate sys` to use the `sys` crate

error[E0432]: unresolved import `sys`
  --> D:\rust\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.5.6\src\raw.rs:29:5
   |
29 | use sys::Termios;
   |     ^^^ maybe a missing crate `sys`?
   |
   = help: consider adding `extern crate sys` to use the `sys` crate

Some errors have detailed explanations: E0432, E0433.
For more information about an error, try `rustc --explain E0432`.
error: could not compile `termion` due to 5 previous errors
warning: build failed, waiting for other jobs to finish...

**Comment by huangyt** [comment]
"behavioral\state", "creational\abstract-factory", "creational\factory-method" had same error.

**Comment by huangyt** [comment]
Oh! It's seems a issue here: https://github.com/osa1/tiny/issues/281#issue-758894604

**Comment by fadeevab** [comment]
@huangyt Sorry to hear it, seems like it has to be ported to Windows. Try to use WSL2 as of now.

**Comment by huangyt** [comment]
OK! still thank you,great work!
